name: ${project.name}
version: ${project.version}
main: nl.svenar.powercamera.PowerCamera
api-version: 1.18
description: ${project.description}
authors: [svenar_nl]
website: ${project.url}
permissions:
    powercamera.hidestartmessages:
        default: not op
    powercamera.bypass.joincamera:
        default: false
libraries:
    - org.spongepowered:configurate-hocon:${configurate.version}
    - org.spongepowered:configurate-gson:${configurate.version}
